/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf
Author: Lorenzo Penco (https://sketchfab.com/Eksmanen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/thefuture-b5fda59eb51341a58da234c24074d2f0
Title: TheFuture
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf');
  const group = useRef();

  // useEffect(() => {
  //   // Resize the camera when the component mounts
  //   const resizeCamera = () => {
  //     const aspect = window.innerWidth / window.innerHeight;
  //     group.current.scale.set(1, aspect, 1);
  //   };
  //   resizeCamera();
  //   window.addEventListener('resize', resizeCamera);
  //   return () => {
  //     window.removeEventListener('resize', resizeCamera);
  //   };
  // }, []);
  return (
    <group {...props} dispose={null} ref={group}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.capelliHIcapelliHIlambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.capelliHIlambert1SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.capelliHIlambert1SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
